version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
  backend:
    build: ./Backend
    ports:
      - "4000:4000"
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASS: Tatiana123456
      DB_NAME: wapoki
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Tatiana123456
      MYSQL_DATABASE: wapoki
    ports:
      - "3306:3306"